name: Gatsby Publish

on:
  schedule:
    - cron:  '*/55 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
      - uses: SvanBoxel/gitlab-mirror-and-ci-action@0.2
        with:
          args: "https://gitlab.com/johnsmithincorp522/johnsmithincorp522.gitlab.io"
        env:
          GITLAB_HOSTNAME: "gitlab.com"
          GITLAB_USERNAME: "johnsmithincorp522"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID: "23711571"
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
